(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* Create global definitions and set up workspace for all subsequent work *)
ClearAll["Global`*"];
SetDirectory[NotebookDirectory[]];
<<setup_workspace.m;
<<setup_definitions.m;


(* Read in baseline parameters and construct baseline shocks then make discreteApprox figure *)
<<setup_params.m;
<<setup_shocks.m;
<<discreteApprox!Plot.m;


(* Set up for solution of 2 period model and construction of figures *)
<<setup_params_2period.m;
<<setup_grids.m;
<<setup_shocks.m;
<<setup_lastperiod.m;
<<setup_PerfectForesightSolution.m;



