(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* Create global definitions and set up workspace for all subsequent work *)
ClearAll["Global`*"];
OpenFigsUsingShell=True;(* If running in batch mode, figures should be opened using shell command *)
If[Length[$FrontEnd] > 0,NBDir=SetDirectory[NotebookDirectory[]];OpenFigsUsingShell=False];
(* If running from the Notebook interface *)
(* If running from shell, must start from inside same directory in which notebook resides *)


<<setup_workspace.m;
(* Read in baseline parameters and construct baseline shocks then make discreteApprox figure *)
<<setup_params.m;
<<setup_shocks.m;


(* ::Input::Initialization:: *)
<<discreteApprox!Plot.m;


<<2Period!Plot.m;


<<2PeriodInt!Plot.m;


<<2periodIntExp!Plot.m;


<<2periodIntExpFOC!Plot.m;


<<2periodIntExpFOCInv!Plot.m;


<<2periodIntExpFOCInvEEE!Plot.m;


<<ExtrapProblem!Plot.m;


<<ExtrapProblemSolved!Plot.m;


<<2PeriodIntExpFOCInvPesReaOpt!Plot.m;


<<2PeriodIntExpFOCInvPesReaOptTighterUpBd!Plot.m;


<<multiperiod!Plot.m;


<<2PeriodIntExpFOCInvPesReaOptTighterUpBdCon!Plot.m;


<<multiperiodCon!Plot.m;


<<multicontrol!Plot.m;






