% setup_everything.m 

global PeriodsToSolve... 
    Rhat n InitialWYRatio InitialWYRatioProb...
    VarInitialLogInc ProbOfAlive LevelAdjustingParameter...
    ThetaMat ThetaMatProb PermMat PermVecProb...
    AlphaVec nP uP GList Betacorr NumOfPeriodsToSimulate NumOfPeople...
    ThetaList PermList stIndicator pi WealthCollege weight
    
setup_params
setup_functions
setup_grid_eee
setup_shocks


