% TakeAverageOf5Obs.m

% Since there are five observations for each household in the data
% generated by STATA (SCF1992_2007_population.dta), 
% averages of the five observations are taken below. 
% Note that some households have observations fewer than five after sample
% selection made using STATA. (This the reason why we need to take a somewhat complicated
% approach as below, when taking averages.)


% Count how many households in original data. Data is copied from STATA data.
NumOfHHs = 1;
for i=2:length(Data)
    if Data(i,1) > Data(i-1,1)
        NumOfHHs = NumOfHHs+1;
    end
end

% Construct data for analysis 
DataAveraged   = zeros(NumOfHHs,size(Data,2));
WeightPos = 3; % Position of weight

denomi = Data(1,WeightPos);
numrat = Data(1,:)*Data(1,WeightPos);
HHPos  = 1;
for j=2:size(Data,1)
      if Data(j,1)==Data(j-1,1) & j<size(Data,1)
         denomi = denomi+Data(j,WeightPos);
         numrat = numrat+Data(j,:)*Data(j,WeightPos);
      elseif Data(j,1)>Data(j-1,1) & j<size(Data,1)
         DataAveraged(HHPos,:) = numrat/denomi;
         DataAveraged(HHPos,WeightPos) = denomi;    % Weight is not mean, but sum
         denomi = Data(j,WeightPos);
         numrat = Data(j,:)*Data(j,WeightPos);
         HHPos  = HHPos+1;
      elseif Data(j,1)==Data(j-1,1) & j==size(Data,1)
         denomi = denomi+Data(j,WeightPos);
         numrat = numrat+Data(j,:)*Data(j,WeightPos);        
         DataAveraged(HHPos,:) = numrat/denomi;
         DataAveraged(HHPos,WeightPos) = denomi;    % Weight is not mean, but sum   
      else
         DataAveraged(HHPos,:) = Data(j,:);  
      end     
end
            